Repository ainize-team/imperatorofmars, pull requests merged in 2025-04, with the labels that each got.

#4 [feat] add web3 wallet connect
  Dashboard/.env.example
  Dashboard/.gitignore
  Dashboard/package.json
  Dashboard/src/app/Web3Providers.tsx
  Dashboard/src/app/layout.tsx
  Dashboard/src/app/page.tsx
  Dashboard/src/components/sections/Navbar.tsx
  Dashboard/yarn.lock
Labels: feature

#9 health check api
  Dashboard/src/app/api/healthcheck/route.ts
Labels: feature

#18 Feature/haechan/GitHub api
  .github/workflows/validate-fol-pr.yml
  Dashboard/.env.example
  Dashboard/package.json
  Dashboard/src/app/api/fol/commit-html/route.ts
  Dashboard/src/app/api/fol/pull-request/route.ts
  Dashboard/src/app/api/fol/validate/route.ts
  Dashboard/src/services/github.service.ts
  Dashboard/yarn.lock
Labels: feature

#17 [feat] mint and register Story NFT
  worldBuilder/.env.example
  worldBuilder/package.json
  worldBuilder/public/asset/kryptoplanet.png
  worldBuilder/src/app/layout.tsx
  worldBuilder/src/app/page.tsx
  worldBuilder/src/lib/constants.ts
  worldBuilder/src/lib/context/AppContext.tsx
  worldBuilder/src/lib/functions/file.ts
  worldBuilder/src/lib/functions/ipfs.ts
  worldBuilder/yarn.lock
Labels: feature

#40 Feature/haechan/html generator agent
  worldBuilder/.env.example
  worldBuilder/package.json
  worldBuilder/src/app/api/fol/commit-html/route.ts
  worldBuilder/src/app/api/fol/pull-request/route.ts
  worldBuilder/src/lib/llm/anthropic.service.ts
  worldBuilder/src/lib/llm/github.service.ts
  worldBuilder/yarn.lock
Labels: feature

#54 [bugfix] fix csr error
  world-builder/src/app/api/ipfs/image/route.ts
  world-builder/src/app/api/ipfs/json/route.ts
  world-builder/src/app/page.tsx
  world-builder/src/components/dagVisualizer.tsx
  world-builder/src/lib/functions/ipfs.ts
Labels: bug

#50 [docs] add readme file
  story-bounty/README.md
  story-bounty/image/0_discover_asset.png
  story-bounty/image/1_1_upload_ipfs.png
  story-bounty/image/1_2_upload_ipfs.png
  story-bounty/image/2_1_mint_register_ip.png
  story-bounty/image/2_2_metamask.png
  world-builder/src/app/page.tsx
Labels: documentation

#61 Fix/haechan/fol file format
  .gitignore
  world-builder/src/app/api/fol/commit-html/route.ts
  world-builder/src/app/api/fol/pull-request/route.ts
  world-builder/src/lib/llm/github.service.ts
Labels: feature
